# Generated by Django 3.2.3 on 2021-05-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pic',
            new_name='picture',
        ),
    ]
