# Generated by Django 3.2.3 on 2021-05-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20210525_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='pic',
        ),
    ]
